language: node_js
node_js:
  - "11.10.1"
stages:
  - test
  - name: prerelease
    if: branch = master
  - name: release
    if: branch = master
  - name: postrelease
    if: branch = master
jobs:
  include:
    - stage: test
      name: "Running automated tests"
      script: npm run test && npm run coverage
    - stage: prerelease
      script: npm run docs
      name: "Building documentation"
      deploy:
        provider: netlify
        site: "f1d48ad6-e89c-455c-9e4e-c6b6d8ddcf6b"
        auth: $NETLIFY_AUTH
        edge: true
        dir: "docs/"
        prod: true
        on:
          branch: master
    - script: npm run build && npm run semantic-release --dry-run
      name: "Releasing library"
    - stage: postrelease
      name: "Purging CDN"
      script: npm run cdn:purge
