language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "11.10.1"
after_success:
  - tasks/after_success.sh
branches:
  only:
    - master
    - develop
deploy:
  provider: netlify
  site: "f1d48ad6-e89c-455c-9e4e-c6b6d8ddcf6b"
  auth: $NETLIFY_AUTH
  edge: true
  dir: "docs/"
  on:
    branch: master
